Project/urls.py
from django.contrib import admin
from django.urls import path, include

# Masukkan urls app kalian

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls'), name="homepage"),
    path('', include('autentikasi.urls')),
    path('transaction/', include('transaction.urls'), name="transaction"),
    path('review/', include('ulasan.urls'), name="review"),
    path('article/', include('article.urls'), name="article"),
    path('category/', include('category.urls'), name='category'),
    path('accounts/', include('allauth.urls'))
]

ulasan/urls.py
from django.urls import path

from . import views

app_name = "ulasan"

urlpatterns = [
    path('', views.index, name='review'),
    path('add/', views.add, name='add'),
    path('get_all/', views.get_all, name='get'),
    path("delete/", views.delete, name="delete")
]

ulasan/models.py
from django.db import models
from homepage.models import Mobil
from django.contrib.auth.models import User
from django.core.validators import MaxValueValidator, MinValueValidator

# Create your models here.

class Review(models.Model):
    username = models.ForeignKey(User, on_delete=models.CASCADE)
    rating = models.PositiveIntegerField(validators=[MinValueValidator(1), MaxValueValidator(5)])
    review = models.CharField(max_length=200)
    mobil = models.ForeignKey(Mobil, on_delete=models.CASCADE)

ulasan/forms.py
from django import forms
from .models import Review

class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = "__all__"
        widgets = {
            'rating' : forms.NumberInput(attrs={
                'min' : 1,
                'max' : 5,
                }),
            }

ulasan/views.py
from django.shortcuts import render, redirect   
from .forms import ReviewForm
from .models import Review
from homepage.models import Mobil
from django.http import JsonResponse, HttpResponse
from django.core import serializers
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required


# Create your views here.

@login_required(login_url="autentikasi:loginPage")
def index(request):
    form = ReviewForm()
    context = {
        'form' : form,
    }
    return render(request, 'ulasan/index.html', context)

@login_required(login_url="autentikasi:loginPage")
def add(request):
    if(request.method == "POST"):
        mobil = Mobil.objects.get(id=request.POST['car_id'])
        form = ReviewForm({
            'username' : request.user,
            'rating' : request.POST['rating'],
            'review' : request.POST['review'],
            'mobil' : mobil
        })
        if(form.is_valid()):
            form.save()
        return JsonResponse({"status" : "SUCCESS"})

@login_required(login_url="autentikasi:loginPage")
def get_all(request):
    reviews = Review.objects.all()
    result = []
    for obj in reviews:
        result.append({
            "username":str(obj.username), 
            "rating":obj.rating, 
            "review":obj.review,
            "mobil":Mobil.objects.get(id=obj.mobil.id).foto,
            "id":obj.id})
    return JsonResponse({"result":result, "user" : str(request.user)})


@login_required(login_url="autentikasi:loginPage")
def delete(request):
    if(request.method == "POST"):
        review = Review.objects.get(id=request.POST['car_id'])
        review.delete()
        return JsonResponse({"status" : "SUCCESS"})

templates/ulasan/index.html
{% extends "base.html" %}
{% load static %}
{% block css %}
<meta name="csrf" content="{{ csrf_token }}">
<meta name="url_get" content="{% url 'ulasan:get' %}">
<meta name="url_add" content="{% url 'ulasan:add' %}">
<meta name="url_base" content="{% url 'ulasan:review' %}">
<meta name="url_del" content="{% url 'ulasan:delete' %}">
<meta name="profile_photo" content="{% static 'ulasan/person.svg' %}">
<link rel="stylesheet" href="{% static 'ulasan/style.css' %}">
<script
src="https://code.jquery.com/jquery-3.4.1.min.js"
integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo="
crossorigin="anonymous"></script>    
{% endblock css %}
{% block title %}Review{% endblock title %}
{% block content %}
<div class="header">
    <a href="#form-box">
        <h4 class="text-center m-0 py-3"><span style="color:#0F4C75">NEW</span> REVIEW</h4>
    </a>
</div>
<div class="row d-flex flex-wrap-reverse">
    <div class="col-12 col-md-5 col-lg-4 form-box p-5" id="form-box">
        <h2 class="text-center mb-5"><span style="color:#0F4C75">NEW</span> REVIEW</h2>
        <form id="review-form">
            <div class="form-row">
                <div class="form-group col">
                    <label for="Rating">RATING</label>
                    {{ form.rating }}
                </div>
            </div>
            <div class="form-group">
                <div class="text-center" style="padding-bottom:10px; font-size:18px;">ULASAN</div>
                {{ form.review }}
            </div>
            <div class="form-group">
                <div class="text-center" style="padding-bottom:10px; font-size:18px;">MOBIL</div>
                {{ form.mobil }}
            </div>
            <div class="d-flex justify-content-center">
                <button type="submit" class="btn bg-dark btn-submit mt-4 rounded-pill">SUBMIT</button>
            </div>
        </form>
    </div>
    <div class="col-12 col-md-7 col-lg-8 review-box p-5 p-md-5">
        <h2 class="title">Customer Reviews</h2>
        <div class="review-content">

        </div>
        {% for i in review %}
        <div class="card mb-4">
            <div class="row m-0">
                <div class="col-3 d-flex flex-column p-0 card-in">
                    <img src="{% static 'ulasan/person.svg' %}" class="person-img">
                    <h5 class="mt-3 mb-0 text-center person-name text-white">{{ i.username }}</h5>
                    <h4 class="mt-1 text-center person-name text-white">{{ i.rating }} / 5</h4>
                </div>
                <div class="col-6 border-left bg-light border-right d-flex align-items-center p-3 border-dark">
                    <h5>{{ i.review }}</h5>
                </div>
                <div class="col-3 bg-light d-flex align-items-center">
                    <img src="{{ i.mobil.foto }}" class="car-img">
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
<script src="{% static 'ulasan/scripts.js' %}"></script>
<script>
    $("input").addClass("form-control")
    $("select").addClass("form-control")
    $("input").eq(0).attr("placeholder", '.../5')
    $("input").eq(1).attr("placeholder", 'Ulasan')
    $("#review-form").submit(function(e) {
        e.preventDefault();
    });
  </script>  
{% endblock content %}