Project/urls.py
from django.contrib import admin
from django.urls import path, include

# Masukkan urls app kalian

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls'), name="homepage"),
    path('', include('autentikasi.urls')),
    path('transaction/', include('transaction.urls'), name="transaction"),
    path('review/', include('ulasan.urls'), name="review"),
    path('article/', include('article.urls'), name="article"),
    path('category/', include('category.urls'), name='category'),
    path('accounts/', include('allauth.urls'))
]

homepage/urls.py
from django.urls import path

from . import views

app_name = "homepage"

urlpatterns = [
    path('', views.homepage, name='homepage'),
    path('getFavCars/', views.get_favorite_cars, name='getfavcars'),
    path('favcars/', views.favcars, name='favcars'),
    path('addFavCar/', views.add, name='addcars'),
    path('deleteFavCar/<str:car_id>', views.deleteFavCar, name='delcars')
]

ulasan/urls.py
from django.urls import path

from . import views

app_name = "ulasan"

urlpatterns = [
    path('', views.index, name='review'),
    path('add/', views.add, name='add'),
    path('get_all/', views.get_all, name='get'),
    path("delete/", views.delete, name="delete")
]

homepage/models.py
from django.db import models
from category.models import Kategori
from django.contrib.auth.models import User

# Create your models here.
class Mobil(models.Model):
    nama_mobil = models.CharField(blank=False, max_length= 100)
    kategori = models.ForeignKey(Kategori, on_delete=models.CASCADE)
    deskripsi = models.CharField(blank=False, max_length= 200)
    tahun = models.IntegerField(blank=False)
    harga = models.IntegerField(blank=False)
    kota = models.CharField(blank=False,max_length=100)
    foto = models.CharField(max_length=400)
    def __str__(self):
        return self.nama_mobil

class FavoriteCars(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    cars = models.ManyToManyField(Mobil)
    def __str__(self):
        return self.user.username

homepage/forms.py
from django import forms
from .models import Mobil

class formulir(forms.ModelForm):
    class Meta:
        model = Mobil
        fields = "__all__"
        widgets = {
            'nama_mobil' : forms.TextInput(attrs={'class': 'form-control'}),
            'kategori' : forms.Select(attrs={'class': 'form-control'}),
            'deskripsi' : forms.TextInput(attrs={'class': 'form-control'}),
            'tahun' : forms.NumberInput(attrs={'class': 'form-control'}),
            'harga' : forms.NumberInput(attrs={'class': 'form-control'}),
            'foto' : forms.TextInput(attrs={'class': 'form-control'}),
            'kota' : forms.TextInput(attrs={'class': 'form-control'}),
        }

homepage/views.py
from django.shortcuts import render,redirect
from . import forms, models
from .models import FavoriteCars, Mobil
from django.http import JsonResponse, HttpResponse
from django.core import serializers
from django.contrib.auth.decorators import login_required

# Create your views here.
def homepage(request):
    mobil = models.Mobil.objects.all()
    context = {
        'mobil' : mobil
    }
    return render(request, 'homepage/index.html', context)

@login_required(login_url="autentikasi:loginPage")
def add(request):
    if request.method == "POST":
        car_id = request.POST["car_id"]
        car = Mobil.objects.get(id=car_id)
        try:
            favCars = FavoriteCars.objects.get(user=request.user)
            favCars.cars.add(car)
            favCars.save()
        except Exception as e:
            favCars = FavoriteCars.objects.create(
                user = request.user,
            )
            favCars.cars.add(car)
            favCars.save()
        return JsonResponse({'status' : 'success'})

@login_required(login_url="autentikasi:loginPage")
def get_favorite_cars(request):
    cars = FavoriteCars.objects.get(user=request.user)
    cars_list = serializers.serialize('json', cars.cars.all())
    return HttpResponse(cars_list, content_type="text/json-comment-filtered")

@login_required(login_url="autentikasi:loginPage")
def favcars(request):
    return render(request, 'homepage/page2.html')

@login_required(login_url="autentikasi:loginPage")
def deleteFavCar(request, car_id):
    if request.method == "POST":
        car = Mobil.objects.get(id=car_id)
        favCars = FavoriteCars.objects.get(user=request.user)
        favCars.cars.remove(car)
        favCars.save()
        return JsonResponse({'status' : 'success'})

templates/homepage/index.html
{% extends "base.html" %}
{% load static %}
{% block css %}
<meta name="url_add" content="{% url 'homepage:addcars' %}">
<meta name="url_del" content="{% url 'homepage:homepage' %}deleteFavCar/">
<meta name="url_get" content="{% url 'homepage:getfavcars' %}">
<meta name="csrf" content="{{ csrf_token }}">
<link rel="stylesheet" href="{% static 'homepage/style.css' %}">
<script src="https://code.jquery.com/jquery-3.4.1.min.js"
  integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous">
</script>
{% endblock css %}
{% block title %}Homepage{% endblock title %}
{% block content %}
<div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img class="d-block w-100" src="static/homepage/pic1s.jpg" alt="First slide" width="2vw">
    </div>
    <div class="carousel-item">
      <img class="d-block w-100" src="static/homepage/pic2s.jpg" alt="Second slide">
    </div>
    <div class="carousel-item">
      <img class="d-block w-100" src="static/homepage/pic3s.jpg" alt="Third slide">
    </div>
    <div class="carousel-item">
      <img class="d-block w-100" src="static/homepage/pic4s.jpg" alt="Third slide">
    </div>
    <div class="carousel-item">
      <img class="d-block w-100" src="static/homepage/pic5s.jpg" alt="Third slide">
    </div>


  </div>
  <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>
<div class="container pt-5">
  <div class="col-md-7 pt-5 pl-2">
    <div class="About">
      About Us
    </div>
    <div class="garis"></div>
  </div>
  <div class="col-md-9 pt-5">
    <div class="tulisan">
      A Web that provides a meeting point from a customer who wants to rent their car in the most easiest ways, and to a
      customer who wants to enjoy a rental car for any needs necessary
    </div>
  </div>
</div>
<div class="container pt-5">
  <div class="col-md-7 pt-5 pl-2">
    <div class="About">
      Car List
    </div>
    <div class="garis"></div><br>
    <div class="garis2"></div>
  </div>
  <div class="col-md-12 pt-5 pl-2 pb-5 mb-5">
    <div class="row">
      {% for i in mobil %}
      <div class="col-md-4 pt-5">
        <div class="card" style="width: 18rem;">
          <img class="card-img-top" src="{{ i.foto }}" alt="Card image cap">
          <div class="card-body">
            <h5 class="card-title">{{i.nama_mobil}}</h5>
            <p class="card-text">Ave Rp {{ i.harga }} / hari</p>
            {% if user.is_authenticated %}
            <img src="{% static 'homepage/beforeLike.svg' %}" height="30" width="30" class="like-car"
              data-car="{{ i.id }}" id="like-{{ i.id }}">
            <img src="{% static 'homepage/afterLike.svg' %}" height="30" width="30" class="unlike-car"
              data-car="{{ i.id }}" id="unlike-{{ i.id }}">
            {% endif %}
          </div>
        </div>
      </div>
      {% endfor %}
    </div>
  </div>
  <script src="{% static 'homepage/script.js' %}"></script>
  {% endblock content %}

templates/homepage/page2.html
{% extends "base.html" %}
{% load static %}
{% block css %}
<meta name="url_del" content="{% url 'homepage:homepage' %}deleteFavCar/">
<meta name="url_get" content="{% url 'homepage:getfavcars' %}">
<meta name="csrf" content="{{ csrf_token }}">
<link rel="stylesheet" href="{% static 'homepage/style.css' %}">
<script src="https://code.jquery.com/jquery-3.4.1.min.js"
  integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous">
  </script>
{% endblock css %}
{% block title %}Homepage{% endblock title %}
{% block content %}
<div class="wrapper p-md-5 p-1">
  <div class="col-md-7 pt-5 pl-2">
    <div class="About">
      Your Favorite Cars
    </div>
    <div class="garis"></div><br>
    <div class="garis2"></div>
  </div>
  <div class="col-md-12 pt-5 pl-2">
    <div class="row fav-cars">
    </div>
  </div>
  
</div>
<script src="{% static 'homepage/script2.js' %}"></script>
{% endblock content %}