Project/urls.py
from django.contrib import admin
from django.urls import path, include

# Masukkan urls app kalian

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls'), name="homepage"),
    path('', include('autentikasi.urls')),
    path('transaction/', include('transaction.urls'), name="transaction"),
    path('review/', include('ulasan.urls'), name="review"),
    path('article/', include('article.urls'), name="article"),
    path('category/', include('category.urls'), name='category'),
    path('accounts/', include('allauth.urls'))
]

article/urls.py
from django.urls import path

from . import views

app_name = "article"

urlpatterns = [
    path('', views.index, name='article'),
    path('detail/<str:pk>', views.detail, name='detail'),
    path('add/', views.add, name='add'),
    path('get_all/', views.get_articles, name='get'),
    path('add_review/<str:pk>', views.add_review, name='add_review'),
    path('get_review/<str:pk>', views.get_review, name='get_review'),
    path('get_score/<str:pk>', views.get_score, name='get_score')
]

autentikasi/urls.py
from django.urls import path

from . import views

app_name = "autentikasi"

urlpatterns = [
    path('login', views.loginPage, name='loginPage'),
    path('register', views.registerPage, name='registerPage'),
    path('logout', views.logoutPage, name='logoutPage'),
]

category/urls.py
from django.urls import path

from . import views

app_name = "category"

urlpatterns = [
    path('', views.index, name='category'),
    path('cari', views.cari,name='cari')
]

homepage/urls.py
from django.urls import path

from . import views

app_name = "homepage"

urlpatterns = [
    path('', views.homepage, name='homepage'),
    path('getFavCars/', views.get_favorite_cars, name='getfavcars'),
    path('favcars/', views.favcars, name='favcars'),
    path('addFavCar/', views.add, name='addcars'),
    path('deleteFavCar/<str:car_id>', views.deleteFavCar, name='delcars')
]

ulasan/urls.py
from django.urls import path

from . import views

app_name = "ulasan"

urlpatterns = [
    path('', views.index, name='review'),
    path('add/', views.add, name='add'),
    path('get_all/', views.get_all, name='get'),
    path("delete/", views.delete, name="delete")
]

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://fonts.googleapis.com/css?family=Roboto:400,700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'base.css' %}">
    {% block css %}{% endblock css %}
    <title>PW Rental - {% block title %}{% endblock title %}</title>
</head>

<body>
    {% include 'navbar.html' %}
    <div class="content">
        {% block content%}

    
        {% endblock content%}    
    </div>
    {% include 'footer.html' %}
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"
    integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous">
    </script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
        crossorigin="anonymous"></script>
</body>

</html>

templates/base2.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    {% block css %}
    
    {% endblock css %}
    <script
    src="https://code.jquery.com/jquery-3.4.1.min.js"
    integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo="
    crossorigin="anonymous"></script>    
    <title>{% block title %}{% endblock title %}</title>
</head>
<body>
    {% include 'navbar.html' %}

    {% block content%}
    
    {% endblock content%}
    {% block js %}
    
    {% endblock js %}
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>
</html>

templates/footer.html
{% load static %}
<div class="contact-us d-flex align-items-center" style="background-color: #151515; height: 10rem">
    <div class="d-flex justify-content-between align-items-center container" style="width: 100%;">
        <h4 style="color: white;">CONTACT<br>US</h4>
        <div class="images">
            <a class="px-2" href=""><img height="40px" src="{% static 'images/gmail.svg' %}"></a>
            <a class="px-2" href=""><img height="40px" src="{% static 'images/instagram.svg' %}"></a>
            <a class="px-2" href=""><img height="40px" src="{% static 'images/whatsapp.svg' %}"></a>
        </div>
    </div>
</div>
<footer class="px-5 pt-2 pb-1" style="background-color: black;">
    <h6 class="text-center text-white">Copyright © Car-Easy 2020 All Rigths Reserved</h6>
</footer>

templates/navbar.html
<nav class="navbar fixed-top navbar-expand-lg navbar-light bg-light px-5">
  <a class="navbar-brand" href="{% url 'homepage:homepage' %}">Car-Easy</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav ml-auto">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'homepage:homepage' %}">Home</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'homepage:favcars' %}">Favorite Car</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'category:category' %}">Search Car</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'ulasan:review' %}">Review</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'article:article' %}">Article</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'transaction:transaction' %}">Transaction</a>
      </li>  
      {% if user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link logout-btn" href="{% url 'autentikasi:logoutPage' %}">{{ request.user }} (Logout)</a>
        </li>  
      {% else %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'autentikasi:loginPage' %}">Login</a>
        </li> 
      {% endif %}
    </ul>
  </div>
</nav>