Project/urls.py
from django.contrib import admin
from django.urls import path, include

# Masukkan urls app kalian

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls'), name="homepage"),
    path('', include('autentikasi.urls')),
    path('transaction/', include('transaction.urls'), name="transaction"),
    path('review/', include('ulasan.urls'), name="review"),
    path('article/', include('article.urls'), name="article"),
    path('category/', include('category.urls'), name='category'),
    path('accounts/', include('allauth.urls'))
]

article/urls.py
from django.urls import path

from . import views

app_name = "article"

urlpatterns = [
    path('', views.index, name='article'),
    path('detail/<str:pk>', views.detail, name='detail'),
    path('add/', views.add, name='add'),
    path('get_all/', views.get_articles, name='get'),
    path('add_review/<str:pk>', views.add_review, name='add_review'),
    path('get_review/<str:pk>', views.get_review, name='get_review'),
    path('get_score/<str:pk>', views.get_score, name='get_score')
]

ulasan/urls.py
from django.urls import path

from . import views

app_name = "ulasan"

urlpatterns = [
    path('', views.index, name='review'),
    path('add/', views.add, name='add'),
    path('get_all/', views.get_all, name='get'),
    path("delete/", views.delete, name="delete")
]

article/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import MaxValueValidator, MinValueValidator

# Create your models here.

class Article(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    motto = models.CharField(max_length=100)
    image = models.CharField(max_length=400)
    date = models.DateField(auto_now_add=True)
    content = models.TextField()

class ArticleReview(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    score = models.PositiveIntegerField(validators=[MinValueValidator(1), MaxValueValidator(5)])

article/forms.py
from django import forms
from .models import Article

class formulir(forms.ModelForm):
    class Meta:
        model = Article   
        fields="__all__"       

article/views.py
from django.shortcuts import render, redirect
from .models import Article, ArticleReview
from . import forms
from django.http import JsonResponse, HttpResponse
from django.core import serializers
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
# Create your views here.

@login_required(login_url="autentikasi:loginPage")
def index(request):
    VarA = forms.formulir()
    VarA_dictio = {
        'formulir' : VarA,
    }
    return render(request, 'article/index.html', VarA_dictio)

@login_required(login_url="autentikasi:loginPage")
def detail(request, pk):
    article = Article.objects.get(id=pk)
    context = {'article' : article}
    return render(request, 'article/detail.html', context)

@login_required(login_url="autentikasi:loginPage")
def add(request):
    if request.method == "POST":
        form = forms.formulir({
            'author' : request.user,
            'title' : request.POST['title'],
            'motto' : request.POST['motto'],
            'image' : request.POST['image'],
            'content' : request.POST['content'],
        })
        if(form.is_valid()):
            form.save()
        return JsonResponse({'status' : 'success'})

@login_required(login_url="autentikasi:loginPage")
def get_articles(request):
    articles = Article.objects.all()
    article_list = serializers.serialize('json', articles)
    return HttpResponse(article_list, content_type="text/json-comment-filtered")

@login_required(login_url="autentikasi:loginPage")
def get_score(request, pk):
    article = Article.objects.get(id=pk)
    review = ArticleReview.objects.filter(article=article)
    score = "Unreviewed"
    if len(review) > 0:
        score = 0
        for obj in review:
            score+=obj.score
        score = round(score/len(review),2)
    return JsonResponse({'score' : score})

@login_required(login_url="autentikasi:loginPage")
def add_review(request, pk):
    if request.method == "POST":
        article = Article.objects.get(id=pk)
        user = request.user
        score = request.POST["score"]
        try:
            review = ArticleReview.objects.get(article=article, user=request.user)
            review.score = score
            review.save()
        except:
            article = ArticleReview.objects.create(
                article = article,
                user = user,
                score = score
            )
        return JsonResponse({'status' : 'success'})  
        
@login_required(login_url="autentikasi:loginPage")
def get_review(request,pk):
    article = Article.objects.get(id=pk)
    reviews = ArticleReview.objects.filter(article=article)
    result = []
    for obj in reviews:
        print(result.append({"user":str(obj.user), "score":obj.score}))
    return JsonResponse({"result":result})

templates/article/detail.html
{% extends "base2.html" %}
{% load static %}
{% block css %}
<meta name="csrf" content="{{ csrf_token }}">
<meta name="url_base" content="{% url 'article:article' %}">
<meta name="url_add" content="{% url 'article:add_review' article.id %}">
<meta name="url_get" content="{% url 'article:get_review' article.id %}">
<link rel="stylesheet" href="{% static 'article/style.css' %}">
{% endblock css %}
{% block title %}Jakarta{% endblock title %}
{% block content %}
<div class="content pt-5">
    <div class="pt-5 row">
        <h1 class="px-2"><span style="color: #9C2208; font-size: larger"><b>{{ article.title }}</b></span><br><i>{{ article.motto }}</i><br><span style="font-size: large">{{ article.author }} | {{ article.date }}</span></h1>
    </div>
    <div class="row">
        <div class="d-flex justify-content-center w-100">
            <img class="img-responsive" src="{{ article.image }}" width="100%" height="auto">
        </div>
        <div class="w-100 break"></div>
        <div class="col-sm">
            <p style="text-align: justify">{{ article.content }}
            </p>
        </div>
    </div>
</div>
<div class="container mt-5" id="Post">
    <h2>Review this article:</h2>
    <div class="col-md-3">
      <div class="form-group">
        <label for="title">Give it score!</label>
        <select class="form-control" id="score">
            <option value="1">1</option>
            <option value="2">2</option>
            <option value="3">3</option>
            <option value="4">4</option>
            <option value="5">5</option>
          </select>
      </div>
      <button type="submit" class="btn btn-primary mb-4 btn-add-review">Submit</button>
    </div>
  </div>
  <div class="container mb-5">

      <table class="table mb-5">
      <thead>
        <tr>
          <th scope="col">#</th>
          <th scope="col">Username</th>
          <th scope="col">Score</th>
        </tr>
      </thead>
      <tbody>
      </tbody>
    </table>
  </div>
  <script src="{% static 'article/scripts2.js' %}"></script>
  {% include 'footer.html' %}

{% endblock content %}

templates/article/index.html
{% extends "base2.html" %}
{% load static %}
{% block css %}
<meta name="csrf" content="{{ csrf_token }}">
<meta name="url_get" content="{% url 'article:get' %}">
<meta name="url_add" content="{% url 'article:add' %}">
<meta name="url_base" content="{% url 'article:article' %}">
<link rel="stylesheet" href="{% static 'article/style.css' %}">

{% endblock css %}
{% block title %}Article{% endblock title %}
{% block content %}
<div style="margin-top: 5rem;" class="p-md-5 p-1">
  <div class="p-5 upper">
    <h1><span style="color: #9C2208"><b>Car?</b></span> Check.<br><span style="color: #9C2208"><b>Places to
          visit?</b></span> Don't worry, we've got you covered.</h1>
  </div>
  <div class="">
    <div class="article-container d-flex flex-wrap">
      <!-- Ajax -->
    </div>
    <div class="container mt-5 border-top pt-3" id="Post">
      <h2>Post an Article here:</h2>
      <form method="post">
        <div class="form-group">
          <label for="title">Title</label>
          {{ formulir.title }}
        </div>
        <div class="form-group">
          <label for="motto">Motto</label>
          {{ formulir.motto }}
        </div>
        <div class="form-group">
          <label for="image">Image link</label>
          {{ formulir.image }}
        </div>
        <div class="form-group">
          <label for="content">Content</label>
          {{ formulir.content }}
        </div>
        <button type="submit" id="submit" class="btn btn-primary mb-4 btn-add-article">Submit</button>
      </form>
    </div>
  </div>
</div>
</div>
{% include 'footer.html' %}
{% endblock content %}
{% block js %}
<script src="{% static 'article/scripts.js' %}"></script>
<script>
  $("input").addClass("form-control")
  $("textarea").addClass("form-control")
  $("input").eq(0).attr("placeholder", 'Tittle')
  $("input").eq(1).attr("placeholder", 'Motto')
  $("input").eq(2).attr("placeholder", 'Image Link')
  $("input").eq(3).attr("placeholder", 'Content')
  $("form").submit(function(e) {
    e.preventDefault();
  });

</script>
{% endblock js %}